package br.com.farofa.gm.model;

public enum Phase {
	NOT_ENOUGH_INPUT, PRE_SYLLABIC, PRE_SYLLABIC_IN_TRANSITION, SYLLABIC, SYLLABIC_COM_VALOR_SONORO, SYLLABIC_IN_TRANSITION, SYLLABIC_ALPHABETIC, SYLLABIC_ALPHABETIC_IN_TRANSITION, ALPHABETIC
}
